"""Stage 3: titles — reads story_package.json and writes legacy titles.json."""
from __future__ import annotations

from app.core.logging import get_logger
from app.core.paths import read_json, stage_path, write_json
from app.pipeline.cache import should_skip
from app.pipeline.stages.base import Stage, StageContext
from app.schemas.story import StoryPackage

log = get_logger(__name__)


class TitlesStage(Stage):
    """
    Titles stage — read-only adapter that reads the canonical StoryPackage
    from story_package.json and writes legacy titles.json for downstream
    stages that still expect it.
    """

    name = "titles"
    label = "Titles"

    def run(self, ctx: StageContext) -> dict:
        out = stage_path(ctx.job_id, "titles")
        if should_skip(out):
            return read_json(out)

        # Load the canonical story package generated by ThesisStage
        story_pkg = StoryPackage.model_validate(
            read_json(stage_path(ctx.job_id, "story_package"))
        )

        # Write legacy titles.json
        legacy = story_pkg.to_legacy_title_package()
        write_json(out, legacy)

        chosen = story_pkg.title.candidates[legacy["chosen_index"]]
        log.info("[titles] wrote %d candidates, chosen: %s",
                 len(legacy["candidates"]), chosen.title)
        return legacy
